# Generated by Django 4.2.7 on 2025-07-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresscode_checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancecheck',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', max_length=10),
        ),
    ]
